version: '3'

volumes:
  jenkins-data:

services:
  jenkins:
    image: hhu/jenkins:0.0.1
    build: ./build
    ports:
      - "8080:8080"
    environment:
      - JENKINS_BASE_URL
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"